/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Account : public AccountBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallAccountBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/Account.def
	// Please inherit and implement "class Account : public AccountBase"
class KBENGINEPLUGINS_API AccountBase : public Entity
{
public:
	EntityBaseEntityCall_AccountBase* pBaseEntityCall;
	EntityCellEntityCall_AccountBase* pCellEntityCall;

	uint64 Coin;
	virtual void onCoinChanged(uint64 oldValue) {}
	uint64 Exp;
	virtual void onExpChanged(uint64 oldValue) {}
	uint64 Fame;
	virtual void onFameChanged(uint64 oldValue) {}
	uint16 Level;
	virtual void onLevelChanged(uint16 oldValue) {}

	virtual void OnReqAccountInfo(uint16 arg1, uint64 arg2, uint64 arg3, uint64 arg4) = 0; 
	virtual void OnReqRoleList(const ROLE_LIST& arg1) = 0; 
	virtual void OnReqUnlockRole(uint8 arg1) = 0; 

	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	AccountBase();
	virtual ~AccountBase();

	void attachComponents() override;
	void detachComponents() override;

};

}