/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "KBETypes.h"
#include "MemoryStream.h"
#include "Bundle.h"
#include "DataTypes.h"
namespace KBEngine
{


class KBENGINEPLUGINS_API DATATYPE_CHAT_INFO : DATATYPE_BASE
{
public:
	void createFromStreamEx(MemoryStream& stream, CHAT_INFO& datas);
	void addToStreamEx(Bundle& stream, const CHAT_INFO& v);
};


}