/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/Role.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_RoleBase : public EntityCall
{
public:

	EntityBaseEntityCall_RoleBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_RoleBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_RoleBase : public EntityCall
{
public:

	EntityCellEntityCall_RoleBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_RoleBase();
};

}