/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/ERoom.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_ERoomBase : public EntityCall
{
public:

	EntityBaseEntityCall_ERoomBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_ERoomBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_ERoomBase : public EntityCall
{
public:

	EntityCellEntityCall_ERoomBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_ERoomBase();
};

}