/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/RoomMgr.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_RoomMgrBase : public EntityCall
{
public:

	EntityBaseEntityCall_RoomMgrBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_RoomMgrBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_RoomMgrBase : public EntityCall
{
public:

	EntityCellEntityCall_RoomMgrBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_RoomMgrBase();
};

}