/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class ERoom : public ERoomBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallERoomBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/ERoom.def
	// Please inherit and implement "class ERoom : public ERoomBase"
class KBENGINEPLUGINS_API ERoomBase : public Entity
{
public:
	EntityBaseEntityCall_ERoomBase* pBaseEntityCall;
	EntityCellEntityCall_ERoomBase* pCellEntityCall;



	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	ERoomBase();
	virtual ~ERoomBase();

	void attachComponents() override;
	void detachComponents() override;

};

}