/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"

namespace KBEngine
{


// defined in */scripts/entity_defs/types.xml

typedef uint8 UINT8;

typedef uint16 UINT16;

typedef uint64 UINT64;

typedef uint32 UINT32;

typedef int8 INT8;

typedef int16 INT16;

typedef int32 INT32;

typedef int64 INT64;

typedef FString STRING;

typedef FString KBE_UNICODE;

typedef float FLOAT;

typedef double DOUBLE;

typedef TArray<uint8> PYTHON;

typedef TArray<uint8> PY_DICT;

typedef TArray<uint8> PY_TUPLE;

typedef TArray<uint8> PY_LIST;

typedef TArray<uint8> ENTITYCALL;

typedef TArray<uint8> BLOB;

typedef FVector2D VECTOR2;

typedef FVector VECTOR3;

typedef FVector4 VECTOR4;

typedef uint64 DBID;

class KBENGINEPLUGINS_API ROLE_INFO
{
public:
	uint64 Dbid;
	uint8 RoleType;
	uint8 IsLock;
	uint32 Kill;
	uint32 Death;
	uint32 Assist;
	uint32 Point;
	uint32 PlayCount;

	ROLE_INFO():
	Dbid(0),
	RoleType(0),
	IsLock(0),
	Kill(0),
	Death(0),
	Assist(0),
	Point(0),
	PlayCount(0)
	{
	}

};

class KBENGINEPLUGINS_API ROLE_LIST
{
public:
	TArray<ROLE_INFO> Value;

	ROLE_LIST():
	Value()
	{
	}

};


}