/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class RoomMgr : public RoomMgrBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallRoomMgrBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/RoomMgr.def
	// Please inherit and implement "class RoomMgr : public RoomMgrBase"
class KBENGINEPLUGINS_API RoomMgrBase : public Entity
{
public:
	EntityBaseEntityCall_RoomMgrBase* pBaseEntityCall;
	EntityCellEntityCall_RoomMgrBase* pCellEntityCall;



	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	RoomMgrBase();
	virtual ~RoomMgrBase();

	void attachComponents() override;
	void detachComponents() override;

};

}