/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class SRoom : public SRoomBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallSRoomBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/SRoom.def
	// Please inherit and implement "class SRoom : public SRoomBase"
class KBENGINEPLUGINS_API SRoomBase : public Entity
{
public:
	EntityBaseEntityCall_SRoomBase* pBaseEntityCall;
	EntityCellEntityCall_SRoomBase* pCellEntityCall;



	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	SRoomBase();
	virtual ~SRoomBase();

	void attachComponents() override;
	void detachComponents() override;

};

}